language: c
compiler:
  - clang
  - gcc
env:
  global:
    - MAKEFILE=Makefile
    - RUN_TESTS=true
matrix:
  include:
    - env: MAKEFILE=makefile_mingw_utf8 CC=i586-mingw32msvc-gcc STRIP=i586-mingw32msvc-strip RUN_TESTS=false
before_install:
  # [Ubuntu Packages](http://packages.ubuntu.com/)
  - sudo apt-get update -qq
  - sudo apt-get install -qq mingw32
# - sudo apt-get install -qq mingw-w64 mingw-w64-dev wine
# - sudo apt-get install -qq gcc-mingw-w64
# - sudo apt-get install -qq gcc-mingw-w64-i686
# - sudo apt-get install -qq gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64 mingw-w64-dev
script:
  - make -f $MAKEFILE
# - make -f $MAKEFILE CC=$CC STRIP=$STRIP
  - [ "$RUN_TESTS" == true ] && make testall
